force-app/main/default/objects/Campaign/fields/EcomailCampaignId__c.field-meta.xml
<CustomField>
    <fullName>EcomailCampaignId__c</fullName>
    <label>Ecomail Campaign Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailListId__c.field-meta.xml
<CustomField>
    <fullName>EcomailListId__c</fullName>
    <externalId>true</externalId>
    <label>Ecomail List Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsBounce__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsBounce__c</fullName>
    <label>Ecomail Stats Bounce</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsBounceRate__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsBounceRate__c</fullName>
    <label>Ecomail Stats Bounce Rate</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsClick__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsClick__c</fullName>
    <label>Ecomail Stats Click</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsClickRate__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsClickRate__c</fullName>
    <label>Ecomail Stats Click Rate</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsConversions__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsConversions__c</fullName>
    <label>Ecomail Stats Conversions</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsConversionsValue__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsConversionsValue__c</fullName>
    <label>Ecomail Stats Conversions Value</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsDelivery__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsDelivery__c</fullName>
    <label>Ecomail Delivery Delivery</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsDeliveryRate__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsDeliveryRate__c</fullName>
    <label>Ecomail Delivery Delivery Rate</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsInject__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsInject__c</fullName>
    <label>Ecomail Stats Inject</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsOpen__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsOpen__c</fullName>
    <label>Ecomail Stats Open</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsOpenRate__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsOpenRate__c</fullName>
    <label>Ecomail Stats Open Rate</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsSpam__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsSpam__c</fullName>
    <label>Ecomail Stats Spam</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsSpamRate__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsSpamRate__c</fullName>
    <label>Ecomail Stats Spam Rate</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsTotalClick__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsTotalClick__c</fullName>
    <label>Ecomail Stats Total Click</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsTotalOpen__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsTotalOpen__c</fullName>
    <label>Ecomail Stats Open</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsUnsub__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsUnsub__c</fullName>
    <label>Ecomail Stats Unsub</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailStatsUnsubRate__c.field-meta.xml
<CustomField>
    <fullName>EcomailStatsUnsubRate__c</fullName>
    <label>Ecomail Stats Unsub Rate</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Campaign/fields/EcomailSync__c.field-meta.xml
<CustomField>
    <fullName>EcomailSync__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Synchronize to Ecomail if checked</description>
    <label>Ecomail Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EcomailSync__c.field-meta.xml
<CustomField>
    <fullName>EcomailSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ecomail Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/EcomailSetting__mdt.object-meta.xml
<CustomObject>
    <label>Ecomail Setting</label>
    <pluralLabel>Ecomail Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/EcomailSetting__mdt/fields/EcomailListId__c.field-meta.xml
<CustomField>
    <fullName>EcomailListId__c</fullName>
    <description>For sync contacts from Ecomail to leads</description>
    <label>Ecomail List Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/fields/SyncCampaigns__c.field-meta.xml
<CustomField>
    <fullName>SyncCampaigns__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Campaigns</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EcomailCampaignSynchronizer.cls
public without sharing class EcomailCampaignSynchronizer {
    
    public List<Campaign> getAllCampaignsToSync() {
        String soql = EcomailQueryBuilder.soqlCampaigns(null, null);
        
        return Database.query(soql);
    }

    public List<Campaign> getChangedCampaignsToSync() {
        Datetime since = Datetime.now();
        since.addHours(-2);

        String soql = EcomailQueryBuilder.soqlCampaigns(since, 50000);
        return Database.query(soql);
    }

    public List<Campaign> filterCampaignsToCreate(List<Campaign> allCampaigns) {
        List<Campaign> result = new List<Campaign>();

        for (Campaign campaign : allCampaigns) {
            if (campaign.EcomailCampaignId__c == null) {
                result.add(campaign);
            }
        }

        return result;
    }

    public List<Campaign> filterCampaignsToUpdate(List<Campaign> allCampaigns) {
        List<Campaign> result = new List<Campaign>();

        for (Campaign campaign : allCampaigns) {
            if (campaign.EcomailCampaignId__c != null) {
                result.add(campaign);
            }
        }

        return result;
    }

    public void synchronizeAllCampaignsToEcomail() {
        EcomailSetting__mdt settings = EcomailCustomMetadataUtils.getSettings();

        if (!settings.SyncCampaigns__c) {
            return;
        }

        List<Campaign> allCampaigns = this.getAllCampaignsToSync();
        List<Campaign> campaignsToCreate = this.filterCampaignsToCreate(allCampaigns);
        List<Campaign> campaignsToUpdate = this.filterCampaignsToUpdate(allCampaigns);

        synchronizeCampaigns(campaignsToCreate, campaignsToUpdate);
    }

    public void synchronizeChangedCampaignsToEcomail() {
        EcomailSetting__mdt settings = EcomailCustomMetadataUtils.getSettings();

        if (!settings.SyncCampaigns__c) {
            return;
        }

        List<Campaign> allCampaigns = this.getChangedCampaignsToSync();
        List<Campaign> campaignsToCreate = this.filterCampaignsToCreate(allCampaigns);
        List<Campaign> campaignsToUpdate = this.filterCampaignsToUpdate(allCampaigns);

        synchronizeCampaigns(campaignsToCreate, campaignsToUpdate);
    }

    public void synchronizeCampaignsToEcomail(List<Campaign> campaigns) {
        EcomailSetting__mdt settings = EcomailSetting__mdt.getInstance('Main');

        if (!settings.SyncCampaigns__c) {
            return;
        }

        List<Campaign> campaignsToCreate = this.filterCampaignsToCreate(campaigns);
        List<Campaign> campaignsToUpdate = this.filterCampaignsToUpdate(campaigns);
    }

    public Campaign createCampaign(Campaign campaign) {
        EcomailApi ecomailApi = new EcomailApi();

        String listName = 'SFDC - ' + campaign.Name;

        Integer newListId = ecomailApi.addNewList(listName);
        Integer newCampaignId = ecomailApi.addNewCampaign(campaign.Name, new List<Integer>{ newListId} );

        SObject[] members = new List<SObject>();
        members.addAll((List<SObject>) this.getContactsFromCampaignMembers(campaign.CampaignMembers));
        members.addAll((List<SObject>) this.getLeadsFromCampaignMembers(campaign.CampaignMembers));

        Boolean subscribersResponse = ecomailApi.addSubscriberBulk(
            newListId,
            members
        );

        campaign.EcomailCampaignId__c = newCampaignId;
        campaign.EcomailListId__c = newListId;

        return campaign;
    }

    public void updateCampaign(Campaign campaign) {
        EcomailApi ecomailApi = new EcomailApi();

        SObject[] members = new List<SObject>();
        members.addAll((List<SObject>) this.getContactsFromCampaignMembers(campaign.CampaignMembers));
        members.addAll((List<SObject>) this.getLeadsFromCampaignMembers(campaign.CampaignMembers));

        Boolean subscribersResponse = ecomailApi.addSubscriberBulk(
            campaign.EcomailListId__c,
            members
        );
    }

    public void synchronizeStatsFromEcomail() {
        Campaign[] campaigns = [
            SELECT Id, EcomailCampaignId__c
            FROM Campaign
            WHERE EcomailSync__c = true AND EcomailCampaignId__c != null
        ];

        List<Campaign> toUpdate = new List<Campaign>();

        for (Campaign campaign : campaigns) {
            Campaign updated = this.getStatsForCampaign(campaign);
            toUpdate.add(updated);
        }

        if (!toUpdate.isEmpty()) {
            update toUpdate;
        }
    }

    private Campaign getStatsForCampaign(Campaign campaign) {
        EcomailApi ecomailApi = new EcomailApi();

        EcomailApi.EcomailCampaignStats stats = ecomailApi.getCampaignStats(campaign.EcomailCampaignId__c);
        campaign.EcomailStatsBounce__c = stats.bounce;
        campaign.EcomailStatsBounceRate__c = stats.bounce_rate;
        campaign.EcomailStatsClick__c = stats.click;
        campaign.EcomailStatsClickRate__c = stats.click_rate;
        campaign.EcomailStatsConversions__c = stats.conversions;
        campaign.EcomailStatsConversionsValue__c = stats.conversions_value;
        campaign.EcomailStatsDelivery__c = stats.delivery;
        campaign.EcomailStatsDeliveryRate__c = stats.delivery_rate;
        campaign.EcomailStatsInject__c = stats.inject;
        campaign.EcomailStatsOpen__c = stats.open;
        campaign.EcomailStatsOpenRate__c = stats.open_rate;
        campaign.EcomailStatsSpam__c = stats.spam;
        campaign.EcomailStatsSpamRate__c = stats.spam_rate;
        campaign.EcomailStatsTotalClick__c = stats.total_click;
        campaign.EcomailStatsTotalOpen__c = stats.total_open;
        campaign.EcomailStatsUnsub__c = stats.unsub;
        campaign.EcomailStatsUnsubRate__c = stats.unsub_rate;
        return campaign;
    }

    private List<Contact> getContactsFromCampaignMembers(List<CampaignMember> campaignMembers) {
        List<Contact> contacts = new List<Contact>();

        for (CampaignMember each : campaignMembers) {
            if (each.Type == 'Contact') {
                contacts.add(each.Contact);
            }
        }

        return contacts;
    }

    private List<Lead> getLeadsFromCampaignMembers(List<CampaignMember> campaignMembers) {
        List<Lead> leads = new List<Lead>();

        for (CampaignMember each : campaignMembers) {
            if (each.Type == 'Lead') {
                leads.add(each.Lead);
            }
        }

        return leads;
    }

    private void synchronizeCampaigns(List<Campaign> campaignsToCreate, List<Campaign> campaignsToUpdate ) {
        List<Campaign> updateCampaigns = new List<Campaign>();

        for (Campaign campaign : campaignsToCreate) {
            updateCampaigns.add(this.createCampaign(campaign));
        }

        for (Campaign campaign : campaignsToUpdate) {
            this.updateCampaign(campaign);
        }

        update updateCampaigns;
    }
}