force-app/main/default/objects/EcomailFieldMapping__mdt/EcomailFieldMapping__mdt.object-meta.xml
<CustomObject>
    <label>Ecomail Field Mapping</label>
    <pluralLabel>Ecomail Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/EcomailFieldMapping__mdt/fields/EcomailField__c.field-meta.xml
<CustomField>
    <fullName>EcomailField__c</fullName>
    <label>EcomailField</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EcomailFieldMapping__mdt/fields/SfdcField__c.field-meta.xml
<CustomField>
    <fullName>SfdcField__c</fullName>
    <label>SfdcField</label>
    <metadataRelationshipControllingField>EcomailFieldMapping__mdt.SfdcObject__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>EcomailFieldMappings</relationshipLabel>
    <relationshipName>EcomailFieldMappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/EcomailFieldMapping__mdt/fields/SfdcObject__c.field-meta.xml
<CustomField>
    <fullName>SfdcObject__c</fullName>
    <label>SfdcObject</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>EcomailFieldMappings</relationshipLabel>
    <relationshipName>EcomailFieldMappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/EcomailSetting__mdt.object-meta.xml
<CustomObject>
    <label>Ecomail Setting</label>
    <pluralLabel>Ecomail Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/EcomailSetting__mdt/fields/APIKey__c.field-meta.xml
<CustomField>
    <fullName>APIKey__c</fullName>
    <label>API Key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/fields/FromEmail__c.field-meta.xml
<CustomField>
    <fullName>FromEmail__c</fullName>
    <label>From Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/fields/FromName__c.field-meta.xml
<CustomField>
    <fullName>FromName__c</fullName>
    <label>From Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/fields/ReplyToEmail__c.field-meta.xml
<CustomField>
    <fullName>ReplyToEmail__c</fullName>
    <label>Reply To Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/fields/SyncCampaigns__c.field-meta.xml
<CustomField>
    <fullName>SyncCampaigns__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Campaigns</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/fields/SyncContacts__c.field-meta.xml
<CustomField>
    <fullName>SyncContacts__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync contacts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/fields/SyncLeads__c.field-meta.xml
<CustomField>
    <fullName>SyncLeads__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Leads</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EcomailCustomMetadataUtils.cls
public class EcomailCustomMetadataUtils {
    public static EcomailSetting__mdt getSettings() {
        EcomailSetting__mdt settings;

        if(!Test.isRunningTest()) {
            settings = EcomailSetting__mdt.getInstance('Main');
        } else {

            settings = new EcomailSetting__mdt();
            settings.APIKey__c = '<replace_this>';
            settings.FromEmail__c = 'replace_this@replace.com';
            settings.FromName__c = '<replace_this>';
            settings.ReplyToEmail__c = 'replace_this@replace.com';
            settings.SyncContacts__c = true;
            settings.SyncLeads__c = true;
            settings.SyncCampaigns__c = true;
        }

        return settings;
    }

    public static List<EcomailFieldMapping__mdt> getFieldMappings() {
        List<EcomailFieldMapping__mdt> mappings;

        if(!Test.isRunningTest()) {
            mappings = EcomailFieldMapping__mdt.getAll().values();
        } else {
            mappings = new List<EcomailFieldMapping__mdt>();
            EcomailFieldMapping__mdt mappingLead = new EcomailFieldMapping__mdt();
            mappingLead.SfdcObject__c = 'Lead';
            mappingLead.SfdcField__c = 'Id';
            mappingLead.EcomailField__c = 'obj_id';

            EcomailFieldMapping__mdt mappingContact = new EcomailFieldMapping__mdt();
            mappingContact.SfdcObject__c = 'Contact';
            mappingContact.SfdcField__c = 'Id';
            mappingContact.EcomailField__c = 'obj_id';

            mappings.add(mappingLead);
            mappings.add(mappingContact);
        }

        return  mappings;
    }  
}