force-app/main/default/objects/Contact/fields/EcomailSync__c.field-meta.xml
<CustomField>
    <fullName>EcomailSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ecomail Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/EcomailSetting__mdt.object-meta.xml
<CustomObject>
    <label>Ecomail Setting</label>
    <pluralLabel>Ecomail Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/EcomailSetting__mdt/fields/EcomailListIdContacts__c.field-meta.xml
<CustomField>
    <fullName>EcomailListIdContacts__c</fullName>
    <description>Id of ecomail subsriber list where contacts will be importing</description>
    <label>Ecomail List Id Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/fields/EcomailListIdLeads__c.field-meta.xml
<CustomField>
    <fullName>EcomailListIdLeads__c</fullName>
    <label>Ecomail List Id Leads</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/fields/SyncContacts__c.field-meta.xml
<CustomField>
    <fullName>SyncContacts__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync contacts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/EcomailSetting__mdt/fields/SyncLeads__c.field-meta.xml
<CustomField>
    <fullName>SyncLeads__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync Leads</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EcomailContactSynchronizer.cls
public without sharing class EcomailContactSynchronizer {
    public void syncAllContacts() {
        List<String> contactFields = EcomailQueryBuilder.getContactFieldsForSoql();
        
        // build SOQL witl standard and custom fields
        String soql = 'SELECT '
                    + String.join(contactFields, ', ') + 
                    + ' FROM Contact '
                    + ' WHERE EcomailSync__c = true AND Email!=\'\'';
        
        List<Contact> contacts = Database.query(soql);
        this.synchronizeContactsToEcomail(contacts);
    }


    public void synchronizeContactsToEcomail(List<Contact> contacts) {
        EcomailSetting__mdt settings = EcomailCustomMetadataUtils.getSettings();

        if (!settings.SyncContacts__c) {
            return;
        }
        
        Integer ecomailListId = (Integer)settings.EcomailListIdContacts__c ;

        EcomailApi api = new EcomailApi();
        api.addSubscriberBulk(ecomailListId, contacts);
    }

    public void syncAllLeads() {
        List<String> leadFields = EcomailQueryBuilder.getLeadFieldsForSoql();
        
        // build SOQL witl standard and custom fields
        String soql = 'SELECT '
                    + String.join(leadFields, ', ') + 
                    + ' FROM Lead '
                    + ' WHERE EcomailSync__c = true AND Email!=\'\'';
        
        List<Lead> leads = Database.query(soql);
        this.synchronizeLeadsToEcomail(leads);
    }

    public void synchronizeLeadsToEcomail(List<Lead> leads) {
        EcomailSetting__mdt settings = EcomailCustomMetadataUtils.getSettings();

        if (!settings.SyncLeads__c) {
            return;
        }
        
        Integer ecomailListId = (Integer)settings.EcomailListIdLeads__c ;

        EcomailApi api = new EcomailApi();
        api.addSubscriberBulk(ecomailListId, leads);
    } 

    public voud synchronizeEcomailToSfdc() {
        
    }
}